version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - kind/dependency
  - do-not-merge/work-in-progress
  ignore:
  - dependency-name: Microsoft.VSSDK.BuildTools
    versions:
    - 16.10.10
    - 16.10.7
    - 16.9.1035
    - 16.9.1044
    - 16.9.1050
  commit-message:
    prefix: chore
    include: scope
